spring.application.name=api-spring

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/biblioteca}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:QvG89dcL^kmvYvh1%$lJ}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/library
springdoc.swagger-ui.operations-sorter=method
